### ISSUE TITLE
[1.14] Tried to add entity Item but it was marked as removed already

### ISSUE THREAD

**Issue by mrsmn** [whatthedrunk/allthemods#139]
Issue Description:

After upgrading from 1.1 to 1.14 I see the following in the server logs:

```
22:10:36] [Server thread/INFO]: Starting minecraft server version 1.10.2
[22:12:06] [Server thread/INFO]: Loading properties
[22:12:06] [Server thread/INFO]: Default game type: SURVIVAL
[22:12:06] [Server thread/INFO]: Generating keypair
[22:12:06] [Server thread/INFO]: Starting Minecraft server on <ip>:12813
[22:12:06] [Server thread/INFO]: Using epoll channel type
[22:12:22] [Server thread/INFO]: Preparing level "world"
[22:13:03] [Server thread/INFO]: Preparing start region for level 0
[22:13:04] [Server thread/INFO]: Preparing spawn area: 38%
[22:13:05] [Server thread/INFO]: Preparing spawn area: 79%
[22:13:06] [Server thread/INFO]: Done (43.638s)! For help, type "help" or "?"
[22:13:06] [Server thread/INFO]: Starting GS4 status listener
[22:13:06] [Query Listener #1/INFO]: Query running on <ip>:12813
[22:17:21] [Server thread/WARN]: Keeping entity Sheep that already exists with UUID 8d9399ac-81b1-4c72-ab6c-d75d6414734a
[22:17:22] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:22] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:22] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:22] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:23] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1611) ~[rw.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1515) ~[rw.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:360) ~[atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:267) [lr.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:202) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.IllegalStateException
	at com.rwtema.zoology.phenes.PheneList.serializeNBT(PheneList.java:83) ~[PheneList.class:?]
	at com.rwtema.zoology.phenes.PheneList.serializeNBT(PheneList.java:22) ~[PheneList.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:121) ~[CapabilityDispatcher.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1580) ~[rw.class:?
	... 11 more
[22:17:28] [Server thread/WARN]: Keeping entity Sheep that already exists with UUID 8d9399ac-81b1-4c72-ab6c-d75d6414734a
[22:17:29] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:36] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:38] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:38] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:38] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:38] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:40] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:48] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:54] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:54] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:54] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:17:57] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1611) ~[rw.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1515) ~[rw.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:360) ~[atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1012) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.IllegalStateException
	at com.rwtema.zoology.phenes.PheneList.serializeNBT(PheneList.java:83) ~[PheneList.class:?]
	at com.rwtema.zoology.phenes.PheneList.serializeNBT(PheneList.java:22) ~[PheneList.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:121) ~[CapabilityDispatcher.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1580) ~[rw.class:?]
	... 10 more
[22:17:58] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1611) ~[rw.class:?]
	at net.minecraft.entity.Entity.func_70039_c(Entity.java:1515) ~[rw.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:360) ~[atj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:267) [lr.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:202) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.IllegalStateException
	at com.rwtema.zoology.phenes.PheneList.serializeNBT(PheneList.java:83) ~[PheneList.class:?]
	at com.rwtema.zoology.phenes.PheneList.serializeNBT(PheneList.java:22) ~[PheneList.class:?]
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:121) ~[CapabilityDispatcher.class:?]
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1580) ~[rw.class:?]
	... 11 more
[22:18:04] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:18:17] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:18:21] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:18:21] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:18:21] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
[22:18:21] [Server thread/WARN]: Tried to add entity Item but it was marked as removed already
```
As you can see, the error is not critical because it doesn't make the server crash but it just keeps spamming the console. Do you have any idea what could cause this?

Version of All the Mods:
1.14

Added mods (Optifine, Fastcraft, etc.):
None

**Comment by whatthedrunk** [comment]
Tonight's update actually removs Zoology so feel free to remove it locally if its having issues. You can just take it off the server without any issues. Thanks for the report!
