### ISSUE TITLE
[1.10.2] Crash on World Load

### ISSUE THREAD

**Issue by snaiperskaya** [whatthedrunk/allthemods#23]
Hi!

I created a server and started playing last night (V0.5) and things went fairly smooth. Today I keep getting the following JEI NullPointerException within about 5 seconds of joining the server:

```
[19:55:01] [Client thread/INFO] [JEI]: Registering plugin: mezz.jei.plugins.vanilla.VanillaPlugin
[19:55:01] [Client thread/ERROR] [JEI]: Null item in itemStack
java.lang.NullPointerException
	at mezz.jei.util.StackHelper.getSubtypes(StackHelper.java:214) [StackHelper.class:?]
	at mezz.jei.plugins.vanilla.furnace.SmeltingRecipeMaker.getFurnaceRecipes(SmeltingRecipeMaker.java:30) [SmeltingRecipeMaker.class:?]
	at mezz.jei.plugins.vanilla.VanillaPlugin.register(VanillaPlugin.java:100) [VanillaPlugin.class:?]
	at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:169) [ProxyCommonClient.class:?]
	at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:142) [ProxyCommonClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_605_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:68) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:159) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1127) [aid.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:195) [bln.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359) [bcx.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276) [bll.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) [gw.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) [gw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[19:55:01] [Client thread/INFO] [JEI]: Registered  plugin: mezz.jei.plugins.vanilla.VanillaPlugin in 0 seconds
[19:55:01] [Client thread/INFO] [JEI]: Registering plugin: de.ellpeck.actuallyadditions.mod.jei.JEIActuallyAdditionsPlugin
[19:55:01] [Client thread/INFO] [JEI]: Registered  plugin: de.ellpeck.actuallyadditions.mod.jei.JEIActuallyAdditionsPlugin in 0 seconds
[19:55:01] [Client thread/INFO] [JEI]: Registering plugin: crazypants.enderio.jei.JeiPlugin
[19:55:01] [Client thread/INFO] [EnderIO]: PainterRecipeCategory: Added 3038 painter recipes in 112 groups to JEI in 0.082 seconds.
[19:55:02] [Client thread/INFO] [EnderIO]: DarkSteelUpgradeRecipeCategory: Added 225 dark steel upgrade recipes to JEI in 0.032 seconds.
[19:55:02] [Client thread/INFO] [EnderIO]: TankRecipeCategory: Added 1833 tank recipes to JEI in 0.326 seconds.
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: crazypants.enderio.jei.JeiPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: forestry.apiculture.compat.ApicultureJeiPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: forestry.apiculture.compat.ApicultureJeiPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: team.chisel.common.integration.jei.ChiselJEIPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: team.chisel.common.integration.jei.ChiselJEIPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: com.rwtema.extrautils2.crafting.jei.XUJEIPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: com.rwtema.extrautils2.crafting.jei.XUJEIPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: gigaherz.enderthing.integration.JEIPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: gigaherz.enderthing.integration.JEIPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: forestry.plugins.compat.ForestryJeiPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: forestry.plugins.compat.ForestryJeiPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: slimeknights.tconstruct.plugin.jei.JEIPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: slimeknights.tconstruct.plugin.jei.JEIPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: mod.chiselsandbits.integration.mods.JustEnoughItems
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: mod.chiselsandbits.integration.mods.JustEnoughItems in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: net.blay09.mods.cookingforblockheads.compat.jei.JEIAddon
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: net.blay09.mods.cookingforblockheads.compat.jei.JEIAddon in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: mcjty.rftools.jei.RFToolsJeiPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: mcjty.rftools.jei.RFToolsJeiPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: slimeknights.mantle.util.JeiPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: slimeknights.mantle.util.JeiPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: vazkii.botania.client.integration.jei.JEIBotaniaPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: vazkii.botania.client.integration.jei.JEIBotaniaPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: pl.asie.charset.audio.recipe.JEIPluginCharsetAudio
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: pl.asie.charset.audio.recipe.JEIPluginCharsetAudio in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: com.shinoow.abyssalcraft.integration.jei.ACJEIPlugin
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: com.shinoow.abyssalcraft.integration.jei.ACJEIPlugin in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: mcjty.lib.compat.JeiCompatibility
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: mcjty.lib.compat.JeiCompatibility in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: aroma1997.core.integration.jei.SubModule
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: aroma1997.core.integration.jei.SubModule in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: pl.asie.charset.lib.recipe.JEIPluginCharsetLib
[19:55:02] [Client thread/INFO] [JEI]: Registered  plugin: pl.asie.charset.lib.recipe.JEIPluginCharsetLib in 0 seconds
[19:55:02] [Client thread/INFO] [JEI]: Registering plugin: mekanism.client.jei.MekanismJEI
[19:55:03] [Client thread/INFO] [JEI]: Registered  plugin: mekanism.client.jei.MekanismJEI in 0 seconds
[19:55:03] [Client thread/INFO] [JEI]: Registering plugin: com.valkyrieofnight.environmentaltech.gui.integration.JEIETMultiblockPlugin
[19:55:03] [Client thread/INFO] [JEI]: Registered  plugin: com.valkyrieofnight.environmentaltech.gui.integration.JEIETMultiblockPlugin in 0 seconds
[19:55:03] [Client thread/INFO] [JEI]: Registering plugin: exter.fodc.jei.ODCJEIPlugin
[19:55:03] [Client thread/INFO] [JEI]: Registered  plugin: exter.fodc.jei.ODCJEIPlugin in 0 seconds
[19:55:03] [Client thread/INFO] [JEI]: Registering plugin: jeresources.jei.JEIConfig
[19:55:03] [Client thread/WARN]: Couldn't set damage of loot item 1xitem.darkutils.potion@0
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: jeresources.jei.JEIConfig in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: sokratis12GR.ArmorPlus.compat.jei.ArmorPlusPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: sokratis12GR.ArmorPlus.compat.jei.ArmorPlusPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: net.darkhax.darkutils.addons.jei.DarkUtilsJEIPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: net.darkhax.darkutils.addons.jei.DarkUtilsJEIPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: com.m4thg33k.tombmanygraves.JEIIntegration.TombManyGravesPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: com.m4thg33k.tombmanygraves.JEIIntegration.TombManyGravesPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: minetweaker.mods.jei.JEIAddonPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: minetweaker.mods.jei.JEIAddonPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: lumien.randomthings.handler.compability.jei.RandomThingsPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: lumien.randomthings.handler.compability.jei.RandomThingsPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: com.whammich.sstow.compat.jei.SoulShardsJEIPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: com.whammich.sstow.compat.jei.SoulShardsJEIPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: WayofTime.bloodmagic.compat.jei.BloodMagicPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: WayofTime.bloodmagic.compat.jei.BloodMagicPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: mod.flatcoloredblocks.integration.PluginJEI
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: mod.flatcoloredblocks.integration.PluginJEI in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: refinedstorage.jei.RefinedStorageJEIPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: refinedstorage.jei.RefinedStorageJEIPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: ic2.jeiIntegration.SubModule
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: ic2.jeiIntegration.SubModule in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: forestry.factory.recipes.jei.FactoryJeiPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: forestry.factory.recipes.jei.FactoryJeiPlugin in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: mekanism.generators.client.jei.GeneratorsJEI
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: mekanism.generators.client.jei.GeneratorsJEI in 0 seconds
[19:55:04] [Client thread/INFO] [JEI]: Registering plugin: mezz.jei.plugins.jei.JEIInternalPlugin
[19:55:04] [Client thread/INFO] [JEI]: Registered  plugin: mezz.jei.plugins.jei.JEIInternalPlugin in 0 seconds
[19:55:05] [Client thread/ERROR] [JEI]: Found a broken recipe: com.rwtema.extrautils2.crafting.jei.JEIMachine$JEIMachineRecipe@17abaa4d
Output ItemStacks: []
Output Fluids: []
Input ItemStacks: Found an itemStack with a null item. This is an error from another mod.
Input Fluids: []

[19:55:11] [Client thread/INFO]: [CHAT] [TConstruct] Configuration synced with server.
[19:55:16] [Client thread/INFO]: [CHAT] [Botania] Warning: Some decorative blocks are being removed, please migrate to either the vanilla or Quark versions.
[19:55:16] [Client thread/INFO] [FTBLibDev]: Client player ID: 32a13cda-25f1-4a0c-a862-c978300ee4a0 and 1 other players
[19:55:16] [Client thread/INFO] [FTBLib]: Current Mode: default
[19:55:16] [Client thread/INFO] [mcjty.lib.varia.Logging]: Received dimension information from server
[19:55:16] [Client thread/INFO] [mcjty.lib.varia.Logging]: RfToolsDimensionManager.syncFromServer
[19:55:16] [Client thread/INFO] [mcjty.lib.varia.Logging]: Dimension information from server is empty.
[19:55:16] [Client thread/INFO] [mcjty.lib.varia.Logging]: Received dimlet rules from server
[19:55:16] [Client thread/INFO] [STDOUT]: [mcjty.lib.network.SendPreferencesToClientHelper:setPreferences:17]: setPreferences: prefs.getStyle() = STYLE_FLAT_GRADIENT
[19:55:18] [Client thread/INFO]: [CHAT] InvTweaks: Configuration loaded.
[19:55:18] [Client thread/INFO]: [CHAT] §1[Mekanism] §7Using developer build §89.1.0
[19:55:18] [Aroma1997Core VersionChecking/INFO]: [CHAT] Aroma1997Core failed to do VersionChecking. Either there is something wrong with your network connection or with my server.
[19:55:18] [Client thread/INFO] [journeymap]: Requesting World ID
[19:55:18] [Client thread/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[19:55:18] [Client thread/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[19:55:19] [Client thread/INFO] [journeymap]: Loading journeymap.topo.config
[19:55:19] [Client thread/INFO] [journeymap]: Loaded 0 waypoints from C:\Users\aquar_000\Documents\Curse\Minecraft\Instances\All the Mods\journeymap\data\mp\Minecraft~Server\waypoints
[19:55:19] [Client thread/INFO] [journeymap]: Blocks and textures are current
[19:55:19] [Client thread/INFO] [journeymap]: Mapping started in C:\Users\aquar_000\Documents\Curse\Minecraft\Instances\All the Mods\journeymap\data\mp\Minecraft~Server\DIM0. Memory: 5834MB total, 3346MB free 
[19:55:19] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Press [§bJ§f]
[19:55:19] [Client thread/INFO] [journeymap]: JourneyMap: Press [J]
```

I have another person playing who is able to get in fine consistently. I also tried updating the server and clients to V0.6 and again only my client/player is having the issue. I've tried even completely rebuilding the modpack profile and re-installing it, but I get the same thing. My next step is to wipe my player files from the server, but I'd really prefer to avoid that if anyone has any ideas.

Thank you!

**Comment by snaiperskaya** [comment]
I should add that both players are in the same house, to rule out something being in one base that's not in the other. I know I've run into that one in the past as well.

**Comment by Carrots4U** [comment]
What were you doing when it started happening? Was anything new placed?

**Comment by AKTheKnight** [comment]
Do you actually crash or does it just report the NPE?

**Comment by snaiperskaya** [comment]
Nothing new was placed and we're still in the "2 chests and a furnace" stage of play. No fancy machinery or anything yet. 

@AKTheKnight -  what I posted is the end of the log I get, but Java itself crashes when this happens, so it's entirely possible it's not even writing the final error. It's the latest Java 8 x64, again same as the other client that's still working fine. I will try logging into that PC with my account later to see if it's the player or the machine, but either way I'm at a loss of what could be doing this.

**Comment by AKTheKnight** [comment]
Okay if it's a java crash can we then please get a full log, we might be able to help more after seeing it

**Comment by snaiperskaya** [comment]
Alright, I will dig up the full log when I get home tonight and post that here.

**Comment by AKTheKnight** [comment]
Thank you :+1:

**Comment by snaiperskaya** [comment]
So, it doesn't seem to be outputting any logs or crash-reports beyond what I posted above because Java itself is crashing. I tried on another PC with my account and was able to get in fine, so it's definitely this machine.

I'm going to poke at a few things, but I'm open to suggestions as well. I'll update this if I find a fix.

**Comment by whatthedrunk** [comment]
I've noticed a ton of crashes related to 1.8.0_25 java. Make sure to be running version 91 or 92. If it is installed click the Gear icon in curse and click minecraft and click on Jar Launcher to make sure its using one of those. Let me know if that fixes it.

**Comment by snaiperskaya** [comment]
I just uninstalled and reinstalled 91 to confirm that, but the results were the same.

**Comment by whatthedrunk** [comment]
can I see the new log that shows version 91?

**Comment by snaiperskaya** [comment]
You're a genius, friend! I went to pull an FML log and the java version did say 25, which made no sense to me. It turns out the Curse Launcher installs Java 8u25 along with itself and defaults to that.

I manually forced the MC client to look at the Java I installed and it seems to be working now. :D
