### ISSUE TITLE
Server stuck in loop on start

### ISSUE THREAD

**Issue by samololo** [whatthedrunk/allthemods#357]
Issue Description: I updated my server from v1.52 to v1.53b then i tried to connect to it and got a time out. When i checked the server log i get the same lines over and over.

What happens:  Server Loop on start those line are flooding the log :
`at net.minecraft.world.World.func_72964_e(World.java:303) ~[aid.class:?]
at net.minecraft.world.World.func_175726_f(World.java:298) ~[aid.class:?]
at net.minecraft.world.World.func_180495_p(World.java:842) ~[aid.class:?]
at ic2.core.energy.leg.EnergyNetLocalLeg.addTileEntity(EnergyNetLocalLeg.java:219) ~[EnergyNetLocalLeg.class:?]
at ic2.core.energy.leg.EventHandler.onEnergyTileLoad(EventHandler.java:27) ~[EventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
at sonar.core.common.tileentity.TileEntityEnergySidedInventory.onLoad(TileEntityEnergySidedInventory.java:137) ~[TileEntityEnergySidedInventory.class:?]
at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:821) ~[asv.class:?]
at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:798) ~[asv.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:490) ~[atj.class:?]
at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) ~[ChunkIOProvider.class:?]
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) ~[lr.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) ~[lr.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) ~[lr.class:?]`

What you expected to happen: to start ^^

Steps to reproduce:

1. start the server

Version of All the Mods: 1.10.2 v1.53b

**Comment by whatthedrunk** [comment]
Would you try allthemods 1.10.2 v1.54 and let me know it its still broken?

**Comment by samololo** [comment]
It fixed this one but i got a conflict between ender io and soulshard and trying to fix it i broke my world.
I switched the pack on my server i might put the back up on an other time.
But for now i will stay on Skyexchange.
