### ISSUE TITLE
World (1.52b) loads corrupt on latest build (1.56)

### ISSUE THREAD

**Issue by pgudge** [whatthedrunk/allthemods#364]
Issue Description:

World backup from 1.52b gives two missing blocks warrning, fml confirm, then gives a Invalid id 4096

What happens:

> [01:53:13] [Server thread/INFO]: Preparing level "world"
[01:54:19] [Server thread/ERROR]: Exception reading .\world\level.dat
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:448) ~[FMLControlledNamespacedRegistry.class:?]
	at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.loadIds(FMLControlledNamespacedRegistry.java:776) ~[FMLControlledNamespacedRegistry.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.loadFrozenDataToStagingRegistry(PersistentRegistryManager.java:421) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:339) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:327) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:418) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:118) [azz.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:121) [azy.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:224) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]
[01:55:45] [Server thread/WARN]: Couldn't find resource table railcraft:chests/village_workshop

Then asks for me to fml confirm, server then completes the load. Login into the world and lots of blocks/items have changed to something else. Hard stone to draconic fusion blocks, doors missing etc. items still available in NEI.

What you expected to happen: Load like any other update.

Steps to reproduce:

1. Download new 1.56 server
2. Copy backup world from 1.52b
3. Start server
...

Version of All the Mods: 1.56

**Comment by pgudge** [comment]
Had a bit more time to play tonight, my 1.52b world won't start on 1.53, 1.55 or 1.56! But starts up fine on 1.52b

**Comment by Noobsloth** [comment]
https://minecraft.curseforge.com/projects/notenoughids/files/2366220

Add that.

**Comment by pgudge** [comment]
Thanks Noobsloth, will try this evening.

**Comment by whatthedrunk** [comment]
This should be fixed in newer versions please let me know if you have any problems still.
