### ISSUE TITLE
client crash using bucket

### ISSUE THREAD

**Issue by grazazel** [whatthedrunk/allthemods#6]
Hi since update to 0.2.2 have had client crash a couple of time when using them

-- Head --
Thread: Client thread
Stacktrace:
	at ic2.core.IC2BucketHandler.onBucketFill(IC2BucketHandler.java:18)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_338_IC2BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:302)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:160)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:485)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1543)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2176)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1960)

dunno if that part of the log helps

**Comment by Carrots4U** [comment]
Resolved in the newest version
